// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.4
// source: guest.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GuestService_GetGuests_FullMethodName   = "/protobufs.GuestService/GetGuests"
	GuestService_CreateGuest_FullMethodName = "/protobufs.GuestService/CreateGuest"
	GuestService_DeleteGuest_FullMethodName = "/protobufs.GuestService/DeleteGuest"
	GuestService_UpdateGuest_FullMethodName = "/protobufs.GuestService/UpdateGuest"
)

// GuestServiceClient is the client API for GuestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuestServiceClient interface {
	GetGuests(ctx context.Context, in *GetGuestsRequest, opts ...grpc.CallOption) (*GetGuestsResponse, error)
	CreateGuest(ctx context.Context, in *Guest, opts ...grpc.CallOption) (*Guest, error)
	DeleteGuest(ctx context.Context, in *DeleteGuestRequest, opts ...grpc.CallOption) (*DeleteGuestResponse, error)
	UpdateGuest(ctx context.Context, in *Guest, opts ...grpc.CallOption) (*Guest, error)
}

type guestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGuestServiceClient(cc grpc.ClientConnInterface) GuestServiceClient {
	return &guestServiceClient{cc}
}

func (c *guestServiceClient) GetGuests(ctx context.Context, in *GetGuestsRequest, opts ...grpc.CallOption) (*GetGuestsResponse, error) {
	out := new(GetGuestsResponse)
	err := c.cc.Invoke(ctx, GuestService_GetGuests_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestServiceClient) CreateGuest(ctx context.Context, in *Guest, opts ...grpc.CallOption) (*Guest, error) {
	out := new(Guest)
	err := c.cc.Invoke(ctx, GuestService_CreateGuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestServiceClient) DeleteGuest(ctx context.Context, in *DeleteGuestRequest, opts ...grpc.CallOption) (*DeleteGuestResponse, error) {
	out := new(DeleteGuestResponse)
	err := c.cc.Invoke(ctx, GuestService_DeleteGuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestServiceClient) UpdateGuest(ctx context.Context, in *Guest, opts ...grpc.CallOption) (*Guest, error) {
	out := new(Guest)
	err := c.cc.Invoke(ctx, GuestService_UpdateGuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuestServiceServer is the server API for GuestService service.
// All implementations must embed UnimplementedGuestServiceServer
// for forward compatibility
type GuestServiceServer interface {
	GetGuests(context.Context, *GetGuestsRequest) (*GetGuestsResponse, error)
	CreateGuest(context.Context, *Guest) (*Guest, error)
	DeleteGuest(context.Context, *DeleteGuestRequest) (*DeleteGuestResponse, error)
	UpdateGuest(context.Context, *Guest) (*Guest, error)
	mustEmbedUnimplementedGuestServiceServer()
}

// UnimplementedGuestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGuestServiceServer struct {
}

func (UnimplementedGuestServiceServer) GetGuests(context.Context, *GetGuestsRequest) (*GetGuestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGuests not implemented")
}
func (UnimplementedGuestServiceServer) CreateGuest(context.Context, *Guest) (*Guest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGuest not implemented")
}
func (UnimplementedGuestServiceServer) DeleteGuest(context.Context, *DeleteGuestRequest) (*DeleteGuestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGuest not implemented")
}
func (UnimplementedGuestServiceServer) UpdateGuest(context.Context, *Guest) (*Guest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGuest not implemented")
}
func (UnimplementedGuestServiceServer) mustEmbedUnimplementedGuestServiceServer() {}

// UnsafeGuestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuestServiceServer will
// result in compilation errors.
type UnsafeGuestServiceServer interface {
	mustEmbedUnimplementedGuestServiceServer()
}

func RegisterGuestServiceServer(s grpc.ServiceRegistrar, srv GuestServiceServer) {
	s.RegisterService(&GuestService_ServiceDesc, srv)
}

func _GuestService_GetGuests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestServiceServer).GetGuests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestService_GetGuests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestServiceServer).GetGuests(ctx, req.(*GetGuestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestService_CreateGuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Guest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestServiceServer).CreateGuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestService_CreateGuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestServiceServer).CreateGuest(ctx, req.(*Guest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestService_DeleteGuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGuestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestServiceServer).DeleteGuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestService_DeleteGuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestServiceServer).DeleteGuest(ctx, req.(*DeleteGuestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestService_UpdateGuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Guest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestServiceServer).UpdateGuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestService_UpdateGuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestServiceServer).UpdateGuest(ctx, req.(*Guest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuestService_ServiceDesc is the grpc.ServiceDesc for GuestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobufs.GuestService",
	HandlerType: (*GuestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGuests",
			Handler:    _GuestService_GetGuests_Handler,
		},
		{
			MethodName: "CreateGuest",
			Handler:    _GuestService_CreateGuest_Handler,
		},
		{
			MethodName: "DeleteGuest",
			Handler:    _GuestService_DeleteGuest_Handler,
		},
		{
			MethodName: "UpdateGuest",
			Handler:    _GuestService_UpdateGuest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guest.proto",
}
